services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-api
    container_name: user-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: postgres

networks:
  default:
    external: true
    name: ecommerce