version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: shopping-api
    container_name: shopping-api
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopping
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: postgres

networks:
  default:
    external: true
    name: ecommerce