version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: product-api
    container_name: product-api
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: postgres

networks:
  default:
    external: true
    name: ecommerce